# Ingress for the Frontend (no rewrite)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortlink-ingress-frontend
  namespace: shortlink
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

---

# Ingress for the Backend (with rewrite)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortlink-ingress-backend
  namespace: shortlink
  annotations:
    # This rewrite rule strips /api from the request path
    # e.g., /api/users becomes /users
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 80